"""Add MachineHealthStatuses

Revision ID: 31ea2132a2ee
Revises: b544153e600b
Create Date: 2025-03-07 15:37:30.446943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ea2132a2ee'
down_revision: Union[str, None] = 'b544153e600b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'machine_health_statuses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('machine_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['machine_id'], ['machines.id'],),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.create_index('idx_machine_id_created_at', 'machine_health_statuses', ['machine_id', 'created_at'])

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_machine_id_created_at', table_name='machine_health_statuses')

    op.drop_table('machine_health_statuses')
    # ### end Alembic commands ###
