"""add remote_id to Machine

Revision ID: 57f04451dad1
Revises: 31ea2132a2ee
Create Date: 2025-03-11 00:17:09.474360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f04451dad1'
down_revision: Union[str, None] = '31ea2132a2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('remote_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'remote_id')
    # ### end Alembic commands ###
